# Generated by Django 4.2.13 on 2024-07-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_remove_author_authoruser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='Text',
            new_name='text',
        ),
    ]
