# Generated by Django 4.2.13 on 2025-03-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_rename_new_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
